### ISSUE TITLE
Issue writing to EEPROM

### ISSUE THREAD

**Issue by sjc** [LLeny/holani#12]
A ROM image built from the [OldAtAtari Lynx template](https://github.com/oldatatari/template/) will lock-up Holani when attempting to write to the EEPROM. The same ROM run in Handy does not exhibit this issue. (Sorry, I haven't been able to check in any other emulator eg. Felix.)

This appears to be caused by `_lnx_eeprom_write` from [resident/lynxeeprom.s](https://github.com/OldAtAtari/template/blob/main/resident/lynxeeprom.s).

Attached is a .lnx file built from the un-modified template.

[game.lnx.zip](https://github.com/user-attachments/files/17800617/game.lnx.zip)

**Comment by LLeny** [comment]
0x01 => Ee93c46x8,
            0x02 => Ee93c56x8,
            0x03 => Ee93c66x8,
            0x04 => Ee93c76x8,
            0x05 => Ee93c86x8,
            0x81 => Ee93c46x16,
            0x82 => Ee93c56x16,
            0x83 => Ee93c66x16,
            0x84 => Ee93c76x16,
            0x85 => Ee93c86x16,

**Comment by LLeny** [comment]
@sjc Were you able to confirm on your side that setting the correct .lnx header tag fixes your issue?
